config/routes.rb
Rails.application.routes.draw do
  devise_for :customers, module: "customers"
  devise_for :admins, module: "admins"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  namespace :admin do
    root "orders#top"
    resources :genres, except: [:new, :show, :destroy]
    resources :items, except: [:destroy]
    resources :customers, except: [:new, :create, :destroy]
    get "/customers/my_page" => "customers#show"
    resources :orders, only: [:show]
  end

  scope module: :public do
  root "homes#top"
  get "/about" => "homes#about"
  get "/customers/my_page" => "customers#show"
  get "/customers/quit" => "customers#quit"
  patch "/customers/out" => "customers#out"
  resources :customers, only: [:edit, :update, :destroy]
  resources :addresses, except: [:new, :show]
  resources :items,  only: [:index, :show]
  delete "/cart_items/destroy_all" => "cart_items#destroy_all"
  resources :cart_items, only: [:index, :update, :destroy, :create]
  post "/orders/log" => "orders#log"
  get "/orders/complete" => "orders#complete"
  resources :orders, only:[:new, :create, :index, :show]
end
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :cart_items, dependent: :destroy
  has_many :addresses, dependent: :destroy
  has_many :orders, dependent: :destroy
  validates :last_name,  presence: true
  validates :first_name, presence: true
  validates :last_name_kana,  presence: true
  validates :first_name_kana, presence: true
  validates :telephone_number, presence: true, format: { with: /\A\d{10,11}\z/ }
  validates :postal_code,  presence: true, format: { with: /\A\d{7}\z/ }
  validates :address, presence: true



def active_for_authentication?
 super && (is_active == true)
end

end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController
 before_action :authenticate_admin!

 def index
  @customers = Customer.page(params[:page]).per(10)
 end

 def show
  @customer = Customer.find(params[:id])
 end

 def edit
  @customer = Customer.find(params[:id])
 end

 def update
  @customer = Customer.find(params[:id])
  if @customer.update(customer_params)
   redirect_to admin_customer_path
  else
   redirect_to edit_admin_customer_path(@customer)
  end
 end

 private
  def customer_params
   params.require(:customer).permit(:customer_id, :last_name, :first_name, :last_name_kana, :first_name_kana, :email, :postal_code, :address, :telephone_number, :is_active)
  end
end

app/controllers/customers/confirmations_controller.rb
# frozen_string_literal: true

class Customers::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/customers/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Customers::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/customers/passwords_controller.rb
# frozen_string_literal: true

class Customers::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/customers/registrations_controller.rb
# frozen_string_literal: true

class Customers::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/customers/sessions_controller.rb
# frozen_string_literal: true

class Customers::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  protected
  # 会員の論理削除のための記述。退会後は、同じアカウントでは利用できない。
  def reject_customer
    @customer = Customer.find_by(name: params[:customer][:name])
    if @customer
      if @customer.valid_password?(params[:customer][:password]) && (@customer.active_for_authentication? == true)
        redirect_to new_customer_registration
      else
        flash[:notice] = "項目を入力してください"
      end
    end
  end
  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/customers/unlocks_controller.rb
# frozen_string_literal: true

class Customers::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/views/admin/customers/edit.html.erb
<div class="container">
 <h4 class="d-inline bg-light"><%= @customer.first_name %><%= @customer.last_name %>さんの会員情報編集</h4>
 <%= form_with model: @customer, url: admin_customer_path, local: true do |f| %>
 <div class="row">
  <div class="form-group">
  <%= f.label :会員ID %>
  <div class="row">
  <%= @customer.id %>
  </div>
  <div class="form-group">
  <%= f.label :氏名 %>
  <div class="row">
  <%= f.text_field :first_name, class: "form-control col-4" %>
  <%= f.text_field :last_name, class: "form-control col-4"%>
  </div>
  </div>
  <div class="form-group">
  <%= f.label :フリガナ %>
  <div class="row">
  <%= f.text_field :first_name_kana, class: "form-control col-4" %>
  <%= f.text_field :last_name_kana, class: "form-control col-4" %>
  </div>
  </div>
  <div class="form-group">
  <%= f.label :郵便番号 %>
  <div class="row">
  <%= f. text_field :postal_code, class: "form-control col-4" %>
  </div>
  </div>
  <div class="form-group">
  <%= f.label :住所 %>
  <div class="row">
  <%= f.text_field :address, class: "form-control col-8" %>
  </div>
  </div>
  <div class="form-group">
  <%= f.label :電話番号 %>
  <div class="row">
  <%= f.text_field :telephone_number, class: "form-control col-4" %>
  </div>
  </div>
  <div class="form-group">
  <%= f.label :メールアドレス %>
  <div class="row">
  <%= f.text_field :email, class: "form-control col-4" %>
  </div>
  <div class="form-group">
  <%= f.label :会員ステータス %>
  <div class="row">
  <%= f.radio_button :is_active, :true %>
  <%= f.label :is_active, "有効" %>
  <%= f.radio_button :is_active, :false %>
  <%= f.label :is_active, "退会" %>
  </div>
  </div>
  <div class="col-2">
  <%= f.submit :変更を保存, class: "btn btn-success" %>
  </div>
  <% end %>
</div>

app/views/admin/customers/index.html.erb
<div class="container">
 <div class="row">
  <h4 class="d-inline bg-light">会員一覧</h4>
 </div>
 <div class="row">
  <table class="table table-hover text-center">
  <thead>
  <tr>
  <th>会員ID</th>
  <th>氏名</th>
  <th>メールアドレス</th>
  <th>ステータス</th>
  </tr>
  </thead>
  <tbody>
  <% @customers.each do |customer| %>
  <tr>
  <td><%= customer.id %></td>
  <td>
  <%= link_to admin_customer_path(customer) do %>
  <%= customer.first_name %>
  <%= customer.last_name %>
  <% end %>
  </td>
  <td><%= customer.email %></td>
  <td><% if customer.is_active == true %>
  有効
  <% else %>
  退会
  <% end %>
  </td>
  </tr>
  <% end %>
  </tbody>
  </table>
 </div>
<div class="container">
 <div class="row">
 <div class="col-md-4 offset-md-4 py-2  mt-5">
 <%= paginate @customers %>
 </div>
 </div>
 </div>
</div>

app/views/admin/customers/show.html.erb
<div class="container">
 <div class="row">
  <h4 class="d-inline bg-light"><%= @customer.first_name %><%= @customer.last_name %>さんの会員情報</h4>
 </div>
 <div class="col-sm-4">
  <table class="table table-borderless">
  <tbody>
  <tr>
  <td>会員ID</td>
  <td><%= @customer.id %></td>
  </tr>
  <tr>
  <td>氏名</td>
  <td>
  <%= @customer.first_name %>
  <%= @customer.last_name %>
  </td>
  </tr>
  <tr>
  <td>フリガナ</td>
  <td>
  <%= @customer.first_name_kana %>
  <%= @customer.last_name_kana %>
  </td>
  </tr>
  <tr>
  <td>郵便番号</td>
  <td><%= @customer.postal_code %></td>
  </tr>
  <tr>
  <td>住所</td>
  <td><%= @customer.address %></td>
  </tr>
  <tr>
  <td>電話番号</td>
  <td><%= @customer.telephone_number %></td>
  </tr>
  <tr>
  <td>メールアドレス</td>
  <td><%= @customer.email %></td>
  </tr>
  <tr>
  <td>会員ステータス</td>
  <td><% if @customer.is_active == true %>
  有効
  <% else %>
  退会
  <% end %></td>
  </tr>
  </tbody>
  </table>
  </div>
  </div>
  <div class="col-sm-3">
  <%= link_to "編集する", edit_admin_customer_path, class: "btn btn-success" %>
  <%= link_to "注文履歴一覧を見る", admin_root_path, class: "btn btn-primary" %>
</div>
</div>
</div>