config/routes.rb
Rails.application.routes.draw do
  devise_for :customers, module: "customers"
  devise_for :admins, module: "admins"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  namespace :admin do
    root "orders#top"
    resources :genres, except: [:new, :show, :destroy]
    resources :items, except: [:destroy]
    resources :customers, except: [:new, :create, :destroy]
    get "/customers/my_page" => "customers#show"
    resources :orders, only: [:show]
  end

  scope module: :public do
  root "homes#top"
  get "/about" => "homes#about"
  get "/customers/my_page" => "customers#show"
  get "/customers/quit" => "customers#quit"
  patch "/customers/out" => "customers#out"
  resources :customers, only: [:edit, :update, :destroy]
  resources :addresses, except: [:new, :show]
  resources :items,  only: [:index, :show]
  delete "/cart_items/destroy_all" => "cart_items#destroy_all"
  resources :cart_items, only: [:index, :update, :destroy, :create]
  post "/orders/log" => "orders#log"
  get "/orders/complete" => "orders#complete"
  resources :orders, only:[:new, :create, :index, :show]
end
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer
  has_many :orders_details, dependent: :destroy

  enum payment: {
    "クレジットカード" => 0,
    "銀行振込" => 1,
  }

end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
  before_action :authenticate_admin!

 def top
  @orders = Order.page(params[:page]).per(10)
 end

 def show
  @order = Order.find(params[:id])
  @orders_details = @order.orders_details.all
  @sum = 0
  @subtotals = @orders_details.map { |orders_details| (orders_details.price * 1.1).floor * orders_details.quantity }
  @sum = @subtotals.sum
 end

end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/views/admin/orders/show.html.erb
<div class="container">
 <div class="row">
 <h4 class="d-inline bg-light">注文履歴詳細</h4>
 </div>
 <div class="row">
  <div class="col-9">
  <table class="table table-borderless">
  <tbody>
  <tr>
  <td>購入者</td>
  <td>
  <%= link_to @order.customer.first_name + @order.customer.last_name, admin_customer_path(@order.customer.id) %>
  </td>
  </tr>
  <tr>
  <td>配送先</td>
  <td>
  〒<%= @order.postal_code %><%= @order.address %></br>
  <%= @order.name %>
  </td>
  </tr>
  <tr>
  <td>支払方法</td>
  <td><%= @order.payment %></td>
  </tr>
  <tr>
  <td>注文ステータス</td>
  <td></td>
  </tr>
  </tbody>
  </table>
  </div>
 </div>
　<div class="row">
   <div class="col-9">
   <table class="table table-hover">
   <thead>
   <tr>
   <th>商品名</th>
   <th>単価(税込)</th>
   <th>数量</th>
   <th>小計</th>
   <th>製作ステータス</th>
   </tr>
   </thead>
   <% @orders_details.each do |t| %>
   <tbody>
   <tr>
   <td><%= t.item.name %></td>
   <td><%= (t.price * 1.1).floor %></td>
   <td><%= t.quantity %></td>
   <td><%= (t.price * 1.1).floor * t.quantity %></td>
   <td></td>
   </tr>
   </tbody>
   <% end %>
   </table>
  </div>
  <div class="col-sm-3 d-flex">
  <table class="table table-borderless">
  <tbody>
  <tr class="table">
  <td>商品合計</td>
  <td><%= @sum %></td>
  </tr>
  <tr class="table">
  <td>送料</td>
  <td><%= @order.postage %></td>
  </tr>
  <tr class="table">
  <td>請求金額合計</td>
  <td><%= @sum + @order.postage %></td>
  </tr>
  </tbody>
  </table>
  </div>
 </div>
</div>

app/views/admin/orders/top.html.erb
<div class="container">
 <div class="row">
 <h4 class="d-inline bg-light">注文履歴一覧</h4>
 </div>
 <div class="row">
 <table class="table table-hover text-center">
 <thead>
 <tr>
 <th>購入日時</th>
 <th>購入者</th>
 <th>注文個数</th>
 <th>注文ステータス</th>
 </tr>
 </thead>
 <tbody>
 <% @orders.each do |order| %>
 <tr>
 <td><%= link_to order.created_at.strftime('%Y/%m/%d %H:%M:%S'), admin_order_path(order) %></td>
 <td>
 <%= order.customer.first_name %>
 <%= order.customer.last_name %>
 </td>
 <td><%= order.orders_details.sum(:quantity) %></td>
 <td></td>
 <td></td>
 </tr>
 <% end %>
 </tbody>
 </table>
</div>
 <div class="container">
 <div class="row">
 <div class="col-md-4 offset-md-4 py-2  mt-5">
 <%= paginate @orders %>
 </div>
 </div>
 </div>
</div>