config/routes.rb
Rails.application.routes.draw do
  devise_for :customers, module: "customers"
  devise_for :admins, module: "admins"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  namespace :admin do
    root "orders#top"
    resources :genres, except: [:new, :show, :destroy]
    resources :items, except: [:destroy]
    resources :customers, except: [:new, :create, :destroy]
    get "/customers/my_page" => "customers#show"
    resources :orders, only: [:show]
  end

  scope module: :public do
  root "homes#top"
  get "/about" => "homes#about"
  get "/customers/my_page" => "customers#show"
  get "/customers/quit" => "customers#quit"
  patch "/customers/out" => "customers#out"
  resources :customers, only: [:edit, :update, :destroy]
  resources :addresses, except: [:new, :show]
  resources :items,  only: [:index, :show]
  delete "/cart_items/destroy_all" => "cart_items#destroy_all"
  resources :cart_items, only: [:index, :update, :destroy, :create]
  post "/orders/log" => "orders#log"
  get "/orders/complete" => "orders#complete"
  resources :orders, only:[:new, :create, :index, :show]
end
end

app/models/addresse.rb
class Addresse < ApplicationRecord
  belongs_to :customer
  validates :last_name,  presence: true
  validates :first_name, presence: true
  validates :postal_code,  presence: true, format: {with: /\A\d{7}\z/}
  validates :address, presence: true
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :customer
  belongs_to :item
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :cart_items, dependent: :destroy
  has_many :addresses, dependent: :destroy
  has_many :orders, dependent: :destroy
  validates :last_name,  presence: true
  validates :first_name, presence: true
  validates :last_name_kana,  presence: true
  validates :first_name_kana, presence: true
  validates :telephone_number, presence: true, format: { with: /\A\d{10,11}\z/ }
  validates :postal_code,  presence: true, format: { with: /\A\d{7}\z/ }
  validates :address, presence: true



def active_for_authentication?
 super && (is_active == true)
end

end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :items
  validates :name, presence: true
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :genre
  has_many :cart_items, dependent: :destroy
  has_many :orders_details, dependent: :destroy
  attachment :image

  validates :genre_id, presence: true
  validates :name ,presence: true
  validates :introduction, presence: true
  validates :price, presence: true, format: { with: /\A[0-9]+\z/i, }
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer
  has_many :orders_details, dependent: :destroy

  enum payment: {
    "クレジットカード" => 0,
    "銀行振込" => 1,
  }

end

app/models/orders_detail.rb
class OrdersDetail < ApplicationRecord

  belongs_to :order
  belongs_to :item
end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController
 before_action :authenticate_admin!

 def index
  @customers = Customer.page(params[:page]).per(10)
 end

 def show
  @customer = Customer.find(params[:id])
 end

 def edit
  @customer = Customer.find(params[:id])
 end

 def update
  @customer = Customer.find(params[:id])
  if @customer.update(customer_params)
   redirect_to admin_customer_path
  else
   redirect_to edit_admin_customer_path(@customer)
  end
 end

 private
  def customer_params
   params.require(:customer).permit(:customer_id, :last_name, :first_name, :last_name_kana, :first_name_kana, :email, :postal_code, :address, :telephone_number, :is_active)
  end
end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
  before_action :authenticate_admin!

 def index
   @genres = Genre.all
   @genre = Genre.new
 end

 def edit
   @genre = Genre.find(params[:id])
 end

 def create
   genre = Genre.new(genre_params)
   genre.save
   redirect_to admin_genres_path
 end

 def update
   @genre = Genre.find(params[:id])
   if @genre.update(genre_params)
     redirect_to admin_genres_path
   else
     render :edit
   end
 end

 private
 def genre_params
   params.require(:genre).permit(:name)
 end

end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  before_action :authenticate_admin!

 def index
   @items = Item.page(params[:page]).per(10)
 end

 def new
   @item = Item.new
 end

 def create
   @item = Item.new(item_params)
    if @item.save
     redirect_to admin_item_path(@item.id)
    else
     redirect_to new_admin_item_path
    end
 end

 def show
   @item = Item.find(params[:id])
 end

 def edit
   @item = Item.find(params[:id])
 end

 def update
 @item = Item.find(params[:id])
 if @item.update(item_params)
 redirect_to admin_item_path(@item.id)
 else
 redirect_to edit_admin_item_path(@item.id)
 end
 end

 private
 def item_params
   params.require(:item).permit(:genre_id, :image, :name, :introduction, :price)
 end

end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
  before_action :authenticate_admin!

 def top
  @orders = Order.page(params[:page]).per(10)
 end

 def show
  @order = Order.find(params[:id])
  @orders_details = @order.orders_details.all
  @sum = 0
  @subtotals = @orders_details.map { |orders_details| (orders_details.price * 1.1).floor * orders_details.quantity }
  @sum = @subtotals.sum
 end

end

app/controllers/admins/unlocks_controller.rb
# frozen_string_literal: true

class Admins::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected
  def after_sign_in_path_for(resource)
    case resource
    when Customer
      root_path
    when Admin
      admin_root_path
    end
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email, :first_name, :last_name, :first_name_kana, :last_name_kana, :telephone_number, :postal_code, :address])
  end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admins/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admins/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), method: :post %><br />
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NaganoCake</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <nav class="navbar navbar-expand navbar-light bg-light">
        <div class="container">
          <a class="navbar-brand" href="/">
            <span>NaganoCake</span>
          </a>
            <ul class="navbar-nav ml-auto">
              <% if customer_signed_in? %>
              <il class="nav-item">
                <%= link_to "マイページ",customers_my_page_path(current_customer.id), class: "nav-link" %>
              </il>
              <il class="nav-item">
                <%= link_to "商品一覧",items_path, class: "nav-link" %>
              </il>
              <li class="nav-item">
                <%= link_to "カート",cart_items_path, class: "nav-link" %>
              </li>
              <li class="nav-item">
                <%= link_to "ログアウト",destroy_customer_session_path, method: :delete, class: "nav-link" %>
              </li>
              <% elsif admin_signed_in? %>
              <li class="nav-item">
                <%= link_to "商品一覧",admin_items_path, class: "nav-link" %>
              </li>
              <li class="nav-item">
                <%= link_to "会員一覧",admin_customers_path,class: "nav-link" %>
              </li>
              <li class="nav-item">
                <%= link_to "注文履歴一覧",admin_root_path,class: "nav-link" %>
              </li>
              <li class="nav-item">
                <%= link_to "ジャンル一覧",admin_genres_path,class: "nav-link" %>
              </li>
              <li class="nav-item">
                <%= link_to "ログアウト",destroy_admin_session_path, method: :delete, class: "nav-link" %>
              </li>
              <% else %>
              <il class="nav-item">
                <%= link_to "About", about_path, class: "nav-link" %>
              </il>
              <il class="nav-item">
                <%= link_to "商品一覧", items_path, class: "nav-link" %>
              </il>
              <li class="nav-item">
                <%= link_to "新規登録",new_customer_registration_path, class: "nav-link" %>
              </li>
              <li class="nav-item">
                <%= link_to "ログイン",new_customer_session_path, class: "nav-link" %>
              </li>
              <% end %>
            </ul>
          </div>
        </div>
      </nav>
      <p class="notice"><%=notice %></p>
    </header>

    <%= yield %>

    <footer>
      <div class="container mt-5">
        <div class="row" >
        <div class="mx-auto">
          <p>CopyRight nagano-cake.inc</p>
        </div>
      </div>
      </div>
    </footer>
  </body>
</html>